# Generated by Django 3.1.2 on 2020-10-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='transaction',
            new_name='order',
        ),
    ]
