# Generated by Django 3.1.2 on 2020-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201027_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9),
        ),
    ]
